[package]
name = "snafu-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
capnpc = "0.14.7"

[dependencies]
capnpc = "0.14.7"
capnp-rpc = "0.14.1"